import { ArrowRight, Clock3, MapPin } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { StatusBadge } from "./primitives";
import type { Job, WaitlistMatch } from "@/lib/vvs-data";

const statusTone = (status: string) => status.includes("confirm") ? "success" : status.includes("assessment") || status === "held" ? "warning" : status === "cancelled" ? "danger" : "neutral";
export function JobCard({ job }: { job: Job }) { return <Card className="rounded-md p-4 shadow-none transition-transform hover:-translate-y-0.5"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-semibold">{job.title}</h3><StatusBadge tone={statusTone(job.status)}>{job.status.replaceAll("_"," ")}</StatusBadge></div><p className="mt-1 text-sm text-muted-foreground">{job.customer}</p><div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground"><span className="flex items-center gap-1"><Clock3 className="size-3.5"/>{job.duration}</span><span className="flex items-center gap-1"><MapPin className="size-3.5"/>Zone {job.zone}</span></div></div><Button asChild variant="ghost" size="icon" aria-label={`Review ${job.title}`}><Link to="/dashboard/jobs/$jobId" params={{jobId:job.id}}><ArrowRight/></Link></Button></div></Card>; }
export function WaitlistCard({ match, onSelect }: { match: WaitlistMatch; onSelect?: () => void }) { return <button onClick={onSelect} className="grid w-full grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-4 border-b p-4 text-left transition-colors last:border-0 hover:bg-muted/60 focus-visible:outline-none"><div className="grid size-12 place-items-center rounded-full bg-accent font-bold text-accent-foreground">{match.score}%</div><div className="min-w-0"><p className="truncate font-semibold">{match.customer}</p><p className="truncate text-sm text-muted-foreground">{match.title} · Zone {match.zone}</p></div><StatusBadge tone="info">{match.flexibility}</StatusBadge></button>; }
export function Timeline({ items }: { items: {time:string;title:string;customer:string;status:string;tone:string}[] }) { return <div className="relative ml-2 border-l pl-6">{items.map((item,i)=><div className="relative pb-6 last:pb-0" key={`${item.time}-${item.title}`}><span className={`absolute -left-[31px] top-1.5 size-3 rounded-full border-2 border-background ${i===2?"bg-primary":"bg-border"}`}/><div className="grid grid-cols-[58px_minmax(0,1fr)_auto] items-start gap-3"><span className="text-sm font-bold">{item.time}</span><div className="min-w-0"><p className="truncate text-sm font-semibold">{item.title}</p><p className="truncate text-xs text-muted-foreground">{item.customer}</p></div><StatusBadge tone={item.tone as "neutral"|"success"|"warning"|"info"}>{item.status}</StatusBadge></div></div>)}</div>; }
export function PageSkeleton() { return <div className="space-y-6"><Skeleton className="h-10 w-64"/><div className="grid gap-4 md:grid-cols-3"><Skeleton className="h-32"/><Skeleton className="h-32"/><Skeleton className="h-32"/></div><Skeleton className="h-80"/></div>; }
