import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, Home, MapPin, Sparkles, Wrench, Droplets } from "lucide-react";
import { CustomerShell } from "@/components/vvs/customer-shell";
import { ProgressStepper, StatusBadge } from "@/components/vvs/primitives";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";
import { PlumbingScene } from "@/components/vvs/plumbing-scene";

export const Route=createFileRoute("/book")({head:()=>({meta:[{title:"Book plumbing service — Ekström VVS"},{name:"description",content:"Describe your plumbing need and choose an available time in Västerås."},{property:"og:title",content:"Book plumbing service — Ekström VVS"},{property:"og:description",content:"A simple guided plumbing booking experience."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Book});
const steps=["Service","Details","Location","Time","Confirm"];
function Book(){const navigate=useNavigate();const [step,setStep]=useState(0);const [service,setService]=useState<"repair"|"project"|null>(null);const [leaking,setLeaking]=useState<boolean|null>(null);const [message,setMessage]=useState("");const [understood,setUnderstood]=useState(false);const [slot,setSlot]=useState("");const [done,setDone]=useState(false);
const next=()=>setStep(v=>Math.min(4,v+1));
 return <CustomerShell minimal><div className="mx-auto max-w-6xl px-5 py-8 sm:py-12"><ProgressStepper steps={steps} current={step}/><div className={cn("mx-auto mt-10",step===0?"grid max-w-5xl items-center gap-8 lg:grid-cols-[1fr_.82fr]":"max-w-2xl")}>{step===0&&<div className="order-2 overflow-hidden rounded-md border bg-secondary/40 lg:order-1"><PlumbingScene compact mode={service ?? "flow"}/></div>}<div className={step===0?"order-1 lg:order-2":""}>{done?<Confirmation/>:<>
{step===0&&<section className="animate-in fade-in slide-in-from-right-3"><Header title="What type of service do you need?" text="Choose the option that best describes your situation."/><div className="mt-8 grid gap-4 sm:grid-cols-2"><Choice active={service==="repair"} icon={<Wrench/>} title="Repair / Emergency" text="Something needs fixing." onClick={()=>setService("repair")}/><Choice active={service==="project"} icon={<Home/>} title="New Installation / Renovation" text="You’re planning a new installation or renovation." onClick={()=>setService("project")}/></div>{service==="repair"&&<div className="mt-8 animate-in fade-in"><h2 className="text-center text-xl font-bold">Is water leaking right now?</h2><div className="mt-4 grid grid-cols-2 gap-3"><Button size="lg" variant={leaking===true?"destructive":"outline"} onClick={()=>setLeaking(true)}><Droplets/>Yes — Emergency</Button><Button size="lg" variant={leaking===false?"default":"outline"} onClick={()=>setLeaking(false)}>No</Button></div></div>}</section>}
{step===1&&<section className="animate-in fade-in slide-in-from-right-3"><Header title={service==="project"?"Tell us about your project":"What’s happening?"} text="Write naturally — a short description is enough."/><div className="mt-7"><Label htmlFor="request">Your description</Label><Textarea id="request" value={message} onChange={e=>{setMessage(e.target.value);setUnderstood(false)}} className="mt-2 min-h-32 text-base" placeholder="Our kitchen sink is leaking and there’s water under the cabinet."/><Button className="mt-3" variant="secondary" disabled={!message.trim()} onClick={()=>{setUnderstood(false);window.setTimeout(()=>setUnderstood(true),650)}}><Sparkles/>Understand request</Button>{message&&!understood&&<div className="mt-5 flex items-center gap-3 rounded-md bg-muted p-4 text-sm text-muted-foreground"><Sparkles className="size-4 animate-pulse-soft text-primary"/>Understanding your request…</div>}{understood&&<Card className="mt-5 rounded-md border-primary/20 p-5 shadow-none"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold text-primary">REQUEST UNDERSTOOD</p><h3 className="mt-2 text-xl font-bold">{service==="project"?"Kitchen installation project":"Kitchen sink leak"}</h3></div><Check className="size-6 text-success"/></div><div className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><p className="text-muted-foreground">Urgency</p><p className="mt-1 font-semibold">{service==="project"?"Normal":"High"}</p></div><div><p className="text-muted-foreground">Estimated service</p><p className="mt-1 font-semibold">{service==="project"?"Site visit":"60–120 min"}</p></div></div><p className="mt-5 border-t pt-4 text-sm">We just need a few more details.</p></Card>}</div></section>}
{step===2&&<section><Header title="Where should we come?" text="This helps us show times that fit the current route."/><div className="mt-7 space-y-4"><div><Label htmlFor="name">Name</Label><Input id="name" defaultValue="Anna Lindberg" className="mt-2 h-12"/></div><div><Label htmlFor="address">Service address</Label><div className="relative mt-2"><MapPin className="absolute left-3 top-3.5 size-5 text-muted-foreground"/><Input id="address" defaultValue="Källgatan 12, 722 11 Västerås" className="h-12 pl-10"/></div></div><div><Label htmlFor="phone">Phone</Label><Input id="phone" defaultValue="070 123 45 67" className="mt-2 h-12"/></div></div></section>}
{step===3&&<section><Header title="Available times" text="Times are based on the day’s current workload and travel zones."/><div className="mt-7 space-y-6">{[["Today",["14:00","16:30"]],["Tomorrow",["09:00","11:30","14:00"]]].map(([day,times])=><div key={day as string}><h3 className="mb-3 font-semibold">{day as string}</h3><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{(times as string[]).map(t=><button key={t} onClick={()=>setSlot(`${day} · ${t}`)} className={cn("min-h-14 rounded-md border bg-card text-sm font-semibold transition-all hover:-translate-y-0.5",slot===`${day} · ${t}`&&"border-primary bg-accent text-accent-foreground ring-2 ring-primary/15")}>{t}</button>)}</div></div>)}{slot&&<div className="rounded-md bg-success/8 p-4 text-sm"><p className="font-semibold text-success">{slot.split(" · ")[1]} is available</p><p className="mt-1 text-muted-foreground">Your appointment fits our current schedule.</p></div>}</div></section>}
{step===4&&<section><Header title="Check your booking" text="Nothing is confirmed until you press the button below."/><Card className="mt-7 rounded-md p-5 shadow-none"><dl className="grid gap-4 text-sm sm:grid-cols-2">{[["Service",service==="project"?"Project site visit":"Kitchen sink repair"],["Address","Källgatan 12, Västerås"],["Time",slot||"Tomorrow · 09:00"],["Duration",service==="project"?"45 min":"60–120 min"],["Estimated price",service==="project"?"No charge":"1,800–2,600 SEK"],["Note","Estimated price — not a binding quote"]].map(([a,b])=><div key={a}><dt className="text-muted-foreground">{a}</dt><dd className="mt-1 font-semibold">{b}</dd></div>)}</dl></Card></section>}
 <div className="mt-10 flex justify-between gap-3">{step>0?<Button variant="ghost" onClick={()=>setStep(v=>v-1)}><ArrowLeft/>Back</Button>:<span/>}<Button disabled={(step===0&&!service)||(step===1&&!understood)||(step===3&&!slot)} onClick={()=>{if(leaking&&step===0){navigate({to:"/emergency"});return;}if(step===4)setDone(true);else next();}}>{step===4?"Confirm booking":"Continue"}<ArrowRight/></Button></div></>}</div></div></div></CustomerShell>}
function Header({title,text}:{title:string;text:string}){return <div className="text-center"><h1 className="text-3xl font-bold sm:text-4xl">{title}</h1><p className="mx-auto mt-3 max-w-lg text-muted-foreground">{text}</p></div>}
function Choice({active,icon,title,text,onClick}:{active:boolean;icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <button onClick={onClick} className={cn("min-h-52 rounded-md border bg-card p-6 text-left transition-all hover:-translate-y-1 hover:surface-shadow",active&&"border-primary ring-2 ring-primary/15")}><span className={cn("grid size-12 place-items-center rounded-md bg-muted text-primary",active&&"bg-primary text-primary-foreground")}>{icon}</span><h2 className="mt-7 text-lg font-bold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{text}</p></button>}
function Confirmation(){return <div className="py-8 text-center animate-in fade-in"><div className="mx-auto grid size-20 place-items-center rounded-full bg-success text-success-foreground animate-success"><Check className="size-10"/></div><h1 className="mt-6 text-4xl font-bold">You’re booked.</h1><p className="mt-2 text-lg text-muted-foreground">Tuesday, October 6 · 14:00–15:30</p><Card className="mx-auto mt-8 max-w-lg rounded-md p-6 text-left shadow-none"><h2 className="font-bold">Kitchen sink repair</h2><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-muted-foreground">Address</dt><dd className="text-right font-medium">Källgatan 12, Västerås</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Estimated duration</dt><dd className="font-medium">60–120 min</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Estimated price</dt><dd className="font-medium">1,800–2,600 SEK</dd></div></dl><p className="mt-4 text-xs text-muted-foreground">Estimated price — not a binding quote.</p></Card><div className="mt-6 flex justify-center gap-3"><Button>View booking</Button><Button variant="outline">Add to calendar</Button></div></div>}
