import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CalendarCheck, Clock3, ShieldCheck, Wrench, Droplets, type LucideIcon } from "lucide-react";
import { CustomerShell } from "@/components/vvs/customer-shell";
import { CopperVisual } from "@/components/vvs/copper-visual";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head:()=>({meta:[{title:"Ekström VVS — Plumbing help without the waiting"},{name:"description",content:"Book trusted plumbing service in Västerås with clear availability and fast answers."},{property:"og:title",content:"Ekström VVS — Plumbing help without the waiting"},{property:"og:description",content:"Describe what you need and find the right service and next available time."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),
  component: Home,
});
const features: { icon: LucideIcon; title: string; text: string }[] = [{icon:Wrench,title:"Tell us what’s wrong",text:"Simple questions, not a technical form."},{icon:CalendarCheck,title:"Choose a clear time",text:"See realistic availability immediately."},{icon:ShieldCheck,title:"Stay informed",text:"Access, changes and confirmations in one place."}];
function Home(){return <CustomerShell><section className="relative overflow-hidden border-b"><div className="absolute inset-0 grid-paper opacity-50"/><div className="relative mx-auto grid min-h-[calc(100svh-72px)] max-w-7xl items-center gap-6 px-5 py-12 lg:grid-cols-[1.05fr_.95fr] lg:px-8"><div className="max-w-2xl animate-in fade-in slide-in-from-bottom-3 duration-500"><p className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-primary"><span className="size-2 rounded-full bg-success"/>Professional plumbing in Västerås</p><h1 className="text-5xl font-bold leading-[1.04] sm:text-6xl lg:text-7xl">Plumbing help,<br/><span className="text-primary">without the waiting.</span></h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-muted-foreground">Describe what you need. We’ll help find the right service and the next available time.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><Link to="/book">Book a service <ArrowRight/></Link></Button><Button asChild size="lg" variant="outline"><Link to="/emergency"><Droplets className="text-destructive"/>Emergency — water leaking now</Link></Button></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted-foreground"><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-success"/>Certified & insured</span><span className="flex items-center gap-2"><Clock3 className="size-4 text-primary"/>Clear arrival windows</span></div></div><CopperVisual/></div></section><section className="px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold text-primary">VVS FLOW</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Every inquiry gets an outcome.</h2><p className="mt-4 text-muted-foreground">No valuable job gets silently lost. From the first description to a confirmed arrival, every step stays clear.</p></div><div className="grid gap-px overflow-hidden rounded-md border bg-border sm:grid-cols-3">{features.map(({icon:Icon,title,text})=><div key={title} className="bg-card p-6"><Icon className="size-6 text-primary"/><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></div>)}</div></div></div></section></CustomerShell>}
