/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccessTokenRouteImport } from './routes/access.$token'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardInboxRouteImport } from './routes/dashboard.inbox'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardRotRouteImport } from './routes/dashboard.rot'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardWaitlistRouteImport } from './routes/dashboard.waitlist'
import { Route as OfferTokenRouteImport } from './routes/offer.$token'
import { Route as RescheduleTokenRouteImport } from './routes/reschedule.$token'
import { Route as DashboardJobsJobIdRouteImport } from './routes/dashboard.jobs_.$jobId'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard.projects_.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessTokenRoute = AccessTokenRouteImport.update({
  id: '/access/$token',
  path: '/access/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRotRoute = DashboardRotRouteImport.update({
  id: '/rot',
  path: '/rot',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWaitlistRoute = DashboardWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => DashboardRoute,
} as any)
const OfferTokenRoute = OfferTokenRouteImport.update({
  id: '/offer/$token',
  path: '/offer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RescheduleTokenRoute = RescheduleTokenRouteImport.update({
  id: '/reschedule/$token',
  path: '/reschedule/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardJobsJobIdRoute = DashboardJobsJobIdRouteImport.update({
  id: '/jobs_/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/projects_/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/emergency': typeof EmergencyRoute
  '/login': typeof LoginRoute
  '/access/$token': typeof AccessTokenRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rot': typeof DashboardRotRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/offer/$token': typeof OfferTokenRoute
  '/reschedule/$token': typeof RescheduleTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/demo': typeof DemoRoute
  '/emergency': typeof EmergencyRoute
  '/login': typeof LoginRoute
  '/access/$token': typeof AccessTokenRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rot': typeof DashboardRotRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/offer/$token': typeof OfferTokenRoute
  '/reschedule/$token': typeof RescheduleTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/emergency': typeof EmergencyRoute
  '/login': typeof LoginRoute
  '/access/$token': typeof AccessTokenRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rot': typeof DashboardRotRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/waitlist': typeof DashboardWaitlistRoute
  '/offer/$token': typeof OfferTokenRoute
  '/reschedule/$token': typeof RescheduleTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/jobs_/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/projects_/$projectId': typeof DashboardProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/dashboard'
    | '/demo'
    | '/emergency'
    | '/login'
    | '/access/$token'
    | '/dashboard/calendar'
    | '/dashboard/inbox'
    | '/dashboard/jobs'
    | '/dashboard/leads'
    | '/dashboard/projects'
    | '/dashboard/rot'
    | '/dashboard/settings'
    | '/dashboard/waitlist'
    | '/offer/$token'
    | '/reschedule/$token'
    | '/dashboard/'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/demo'
    | '/emergency'
    | '/login'
    | '/access/$token'
    | '/dashboard/calendar'
    | '/dashboard/inbox'
    | '/dashboard/jobs'
    | '/dashboard/leads'
    | '/dashboard/projects'
    | '/dashboard/rot'
    | '/dashboard/settings'
    | '/dashboard/waitlist'
    | '/offer/$token'
    | '/reschedule/$token'
    | '/dashboard'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/dashboard'
    | '/demo'
    | '/emergency'
    | '/login'
    | '/access/$token'
    | '/dashboard/calendar'
    | '/dashboard/inbox'
    | '/dashboard/jobs'
    | '/dashboard/leads'
    | '/dashboard/projects'
    | '/dashboard/rot'
    | '/dashboard/settings'
    | '/dashboard/waitlist'
    | '/offer/$token'
    | '/reschedule/$token'
    | '/dashboard/'
    | '/dashboard/jobs_/$jobId'
    | '/dashboard/projects_/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  EmergencyRoute: typeof EmergencyRoute
  LoginRoute: typeof LoginRoute
  AccessTokenRoute: typeof AccessTokenRoute
  OfferTokenRoute: typeof OfferTokenRoute
  RescheduleTokenRoute: typeof RescheduleTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access/$token': {
      id: '/access/$token'
      path: '/access/$token'
      fullPath: '/access/$token'
      preLoaderRoute: typeof AccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rot': {
      id: '/dashboard/rot'
      path: '/rot'
      fullPath: '/dashboard/rot'
      preLoaderRoute: typeof DashboardRotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/waitlist': {
      id: '/dashboard/waitlist'
      path: '/waitlist'
      fullPath: '/dashboard/waitlist'
      preLoaderRoute: typeof DashboardWaitlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/offer/$token': {
      id: '/offer/$token'
      path: '/offer/$token'
      fullPath: '/offer/$token'
      preLoaderRoute: typeof OfferTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reschedule/$token': {
      id: '/reschedule/$token'
      path: '/reschedule/$token'
      fullPath: '/reschedule/$token'
      preLoaderRoute: typeof RescheduleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/jobs_/$jobId': {
      id: '/dashboard/jobs_/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/dashboard/jobs/$jobId'
      preLoaderRoute: typeof DashboardJobsJobIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects_/$projectId': {
      id: '/dashboard/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardRotRoute: typeof DashboardRotRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWaitlistRoute: typeof DashboardWaitlistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardJobsJobIdRoute: typeof DashboardJobsJobIdRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardRotRoute: DashboardRotRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWaitlistRoute: DashboardWaitlistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardJobsJobIdRoute: DashboardJobsJobIdRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  EmergencyRoute: EmergencyRoute,
  LoginRoute: LoginRoute,
  AccessTokenRoute: AccessTokenRoute,
  OfferTokenRoute: OfferTokenRoute,
  RescheduleTokenRoute: RescheduleTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
